Algoritmo "variaveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Victor correa Saldanha
// Data atual  : 05/05/2020
Var
// Seção de Declarações das variáveis 
  primeiroNome, segundoNome, cidade, endereco: caractere
  idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo